language: go
go:
  - "1.11.x"
env:
  - GO111MODULE=on
install: true
script:
  - make test
  - make
deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux
